### ISSUE TITLE
Error on the permissions page

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui-demo#8]
```
to Drupal\admin_ui_support\Controller\JsonApiRequestHandler::resourceFactory() must be an instance of Symfony\Component\Routing\Route, instance of Drupal\jsonapi\ResourceType\ResourceType given, called in /private/tmp/drupal-admin-ui-demo/docroot/modules/contrib/jsonapi/src/Controller/RequestHandler.php on line 131 in Drupal\admin_ui_support\Controller\JsonApiRequestHandler->resourceFactory() (line 22 of /private/tmp/drupal-admin-ui-demo/docroot/modules/contrib/drupal-admin-ui-support/src/Controller/JsonApiRequestHandler.php) #0 /private/tmp/drupal-admin-ui-demo/docroot/modules/contrib/jsonapi/src/Controller/RequestHandler.php(131): Drupal\admin_ui_support\Controller\JsonApiRequestHandler->resourceFactory(Object(Drupal\jsonapi\ResourceType\ResourceType))

#1 [internal function]: Drupal\jsonapi\Controller\RequestHandler->handle(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\jsonapi\ResourceType\ResourceType))

#2 /private/tmp/drupal-admin-ui-demo/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) 
#3 /private/tmp/drupal-admin-ui-demo/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() 

#4 /private/tmp/drupal-admin-ui-demo/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) 

#5 /private/tmp/drupal-admin-ui-demo

```

**Comment by dawehner** [comment]
I think we are fine.
